version: '1.0'
volumes:
  mysql-volume:
  ghost-volume:

services:
  ghost:
    build: .
    ports:
      - 2368:2368
    networks:
      - ghost
    restart: always
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: '${MYSQL_USER}'
      database__connection__password: '${MYSQL_PASSWORD}'
      database__connection__database: db
      storage__active: s3
      storage__s3__accessKeyId: '${AWS_ACCESS_KEY_ID}'
      storage__s3__secretAccessKey: '${AWS_SECRET_ACCESS_KEY}'
      storage__s3__region: '${AWS_DEFAULT_REGION}'
      storage__s3__bucket: '${GHOST_STORAGE_ADAPTER_S3_PATH_BUCKET}'

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - ghost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'

networks:
  ghost:
